name: Hello World Action

on: [push]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Executando teste"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo Executando build"
